% folder_list = {
% 
% %BLA-Insc-14
% {
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\Pre-RDT RM';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\RDT D1';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\RDT D2';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\RDT D3';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\RM D1';...
% % 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-40\RM D2';...
% % }
% % 
% % 
% % 
% % % 
% % % {
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-03_RM_D1\RM_D1';...
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-18_RDT_D1\RDT_D1';...
% % % }
% % 
% % 
% % 
% % 
% % };
% %
% % 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-30\RM D2';...
% };
% }

% folder_list = {
% 
% %BLA-Insc-14
% {
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-2\Pre-RDT RM';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-2\RDT D1';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-2\RDT D2';...
% % 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-1\RDT D3';...
% 'I:\MATLAB\Sean CNMFe\RG-Insc\RG-Insc-2\RM D1';...
% % 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-40\RM D2';...
% % }
% % 
% % 
% % 
% % % 
% % % {
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-03_RM_D1\RM_D1';...
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-18_RDT_D1\RDT_D1';...
% % % }
% % 
% % 
% % 
% % 
% % };
% %
% % 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-30\RM D2';...
% };
% }


% folder_list = {
% 
% %BLA-Insc-14
% {
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\Pre-RDT RM';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\RDT D1';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\RDT D2';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\RDT D3';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\RM D1';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\RM D2';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-25\SHOCK TEST';...
% % }
% % 
% % 
% % 
% % % 
% % % {
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-03_RM_D1\RM_D1';...
% % % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-18_RDT_D1\RDT_D1';...
% % % }
% % 
% % 
% % 
% % 
% % };
% %
% % 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-30\RM D2';...
% };
% }

folder_list = {

%BLA-Insc-14
{
'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-24\SHOCK TEST';...
};
}
