folder_list = {

%BLA-Insc-14
{
'I:\MATLAB\Sean CNMFe\BLA-NAcSh\BLA-Insc-1\Pre-RDT RM';...
'I:\MATLAB\Sean CNMFe\BLA-NAcSh\BLA-Insc-1\RDT D1';...
'I:\MATLAB\Sean CNMFe\BLA-NAcSh\BLA-Insc-1\RDT D2';...
%'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-39\RDT D3';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-40\RM D1';...
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-40\RM D2';...
% }
% 
% 
% 
% % 
% % {
% % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-03_RM_D1\RM_D1';...
% % 'I:\MATLAB\Sean CNMFe\BLA-Insc-7\2021-05-18_RDT_D1\RDT_D1';...
% % }
% 
% 
% 
% 
% };
%
% 'I:\MATLAB\Sean CNMFe\pan-neuronal BLA\BLA-Insc-30\RM D2';...
};
}